### ISSUE TITLE
[TODO] Change application name

### ISSUE THREAD

**Issue by KevinWai1** [bcgov/PDF-Portfolio-Detector#1]
Find another name that will suit the application

**Comment by vortex-hue** [comment]
Hi @KevinWai1 @LTU-AR is this open for open source developers to contribute too?

**Comment by KevinWai1** [comment]
> Hi @KevinWai1 @LTU-AR is this open for open source developers to contribute too?

Hi @vortex-hue thanks for taking interest in contributing but our repository is not open for public contribution, although we are open for you to fork this project into your own repository to work on. Also, our latest push has completed these TODO's we have in our issues tab!

**Comment by KevinWai1** [comment]
Inside of application we have changed our program to "PDF Detective".
