### ISSUE TITLE
[TODO] Add PDF version into excel output 

### ISSUE THREAD

**Issue by KevinWai1** [bcgov/PDF-Portfolio-Detector#6]
Add PDF version to excel file output (even for PDF's that are not portfolio, form fields or encrypt)

**Comment by vortex-hue** [comment]
HI @KevinWai1, is this open to open source developers like myself to contribute to it?

**Comment by KevinWai1** [comment]
> HI @KevinWai1, is this open to open source developers like myself to contribute to it?

Replied in another TODO

**Comment by KevinWai1** [comment]
Implemented PDF version indication inside of the excel files.
